      SUBROUTINE ANTSYM(X,NA,ISWTCH)
C
C THIS ROUTINE ANTISYMMETRIZES THE LOWER TRIANGLE OF A SQUARE MATRIX X (
C  INCLUDING THE DIAGONAL) AND RETURNS THE RESULT IN PACKED TRIANGULAR F
C
C IF ISWTCH IS SET TO A NON-ZERO VALUE, IT RETURNS THE VALUES OF THE
C  UPPER TRIANGULAR ELEMENTS OF THE ANTISYMMETRIZED MATRIX.
C
CEND
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      DIMENSION X(NA*NA)
C
      IND(I,J)=(J-1)*NA+I
      IPOS(I,J)=I+((J-1)*(J-2))/2
      K=0
      KL=0
      IF(ISWTCH.EQ.0)THEN
       DO 10 I=1,NA
CDIR$ IVDEP
*VOCL LOOP,NOVREC
        DO 20 J=I+1,NA
         K=K+1
         X(K)=X(IND(I,J))-X(IND(J,I))
20      CONTINUE
10     CONTINUE
      ELSE
       DO 30 I=1,NA
CDIR$ IVDEP
*VOCL LOOP,NOVREC
        DO 40 J=I+1,NA
         K=K+1
         X(K)=X(IND(J,I))-X(IND(I,J))
40      CONTINUE
30     CONTINUE
      ENDIF
CDIR$ IVDEP
*VOCL LOOP,NOVREC
      DO 200 JIND=1,K
       X(K+JIND)=X(JIND)
200   CONTINUE
C      CALL SSWAP(K*IINTFP,X,1,X(K+1),1)
      DO 50 I=1,NA
CDIR$ IVDEP
*VOCL LOOP,NOVREC
       DO 60 J=I+1,NA
        KL=KL+1
        X(IPOS(I,J))=X(K+KL)
60     CONTINUE
50    CONTINUE
      RETURN
      END
