
C PRIMITIVE ROUTINE USED BY THE FANCY I/O ROUTINES.  REST ASSURED THAT
C YOU WILL NEVER WANT TO KNOW WHAT THIS ROUTINE DOES.

      SUBROUTINE FILIRP(IVEC,IRREP)
      IMPLICIT INTEGER (A-Z)
      DIMENSION IVEC(4)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPX(255,2),DIRPRD(8,8)
      IVEC(1) = DIRPRD(IVEC(2),IRREP)
      IF (IVEC(3).EQ.0) IVEC(3) = DIRPRD(IVEC(4),IRREP)
      IF (IVEC(4).EQ.0) IVEC(4) = DIRPRD(IVEC(3),IRREP)
      RETURN
      END
