      SUBROUTINE SORTT1(ICORE,MAXCOR,ISPIN,ILIST,NTOP,TYPE)
C
C DRIVER FOR ROUTINE WHICH PICKS UP THE T1 VECTOR FROM DISK FOR A 
C  SPIN CASE AND FIND THE NTOP LARGEST ELEMENTS BY MAGNITUDE.  THESE ARE
C  PRINTED OUT AT THE END OF THE ROUTINE.
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHARACTER*8 LABEL1
      CHARACTER*1 TYPE
      DIMENSION ICORE(MAXCOR)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /INFO/ NOCCO(2),NVRTO(2)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      NOCC=NOCCO(ISPIN)
      NVRT=NVRTO(ISPIN)
      NT1SIZ=IRPDPD(1,8+ISPIN)
      IF(ISPIN.EQ.1)THEN
       NSMSZ=NVRT*NOCC
       LABEL1='SVAOA2  '
      ELSEIF(ISPIN.EQ.2)THEN
       NSMSZ=NVRT*NOCC
       LABEL1='SVBOB2  '
      ENDIF
C
C ALLOCATE CORE FOR T VECTOR, SYMMETRY VECTORS AND INDICES.
C
      I000=1
      I010=I000+IINTFP*NT1SIZ
      I020=I010+IINTFP*NTOP
      I030=I020+NSMSZ
      I040=I030+NTOP
      I050=I040+NTOP
      I060=I050+NTOP
      CALL GETREC(20,'JOBARC',LABEL1,NSMSZ,ICORE(I020))
      CALL TOPT1S(ISPIN,ILIST,NTOP,NT1SIZ,NOCC,
     &            NVRT,NSMSZ,ICORE(I000),ICORE(I010),
     &            ICORE(I020),ICORE(I030),ICORE(I040),ICORE(I050),
     &            TYPE)
      RETURN
      END
