      SUBROUTINE SYTRA(A,DISSIZE,NUM1,NUM2,SCR)
C
C   THIS ROUTINE COMPUTES THE TRANSPOSE OF A GIVEN MATRIX
C
C    A(DISSIZE,IJ) ----> A(DISSIZE,JI)
C
C    WHERE     NUM1 AND NUM2 GIVE THE NUMBER OF DIFFERENT
C              I AND J INDICES RESPECTIVELY
C
C    SCR IS AN SCRATCH ARRAY OF LENGTH NUM1*NUM2
C
C    NOTE THIS ROUTINE IS USED IN OUT-CORE ALGORITHMN WHERE
C    ONLY ONE SUB BLOCK OF THE A-MATRIX WITHIN ONE GIVEN
C    SYMMETRY IS AVAILABLE
C
CEND
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INTEGER DISSIZE
      DIMENSION A(DISSIZE,1),SCR(1)
C
      DO 100 L=1,DISSIZE
      DO 10 J=1,NUM2
      DO 10 I=1,NUM1
      IND1=(J-1)*NUM1+I
      IND2=(I-1)*NUM2+J
      SCR(IND2)=A(L,IND1)
10    CONTINUE
      DO 20 IJ=1,NUM1*NUM2
      A(L,IJ)=SCR(IJ)
20    CONTINUE
100   CONTINUE
      RETURN
      END  
