      SUBROUTINE T2INS2(TAU,OVRLP,Z,IOVOFF,NROWT,NCOLT,IRREPDO)
C
C  FORM Z(A,j) = SUM TAU(bA,Ij) * DELTA(I,b)
C                b,I
C
CEND

      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DIRPRD,POP,VRT,POPI,POPJ,VRTA,VRTB,A,B
      DIMENSION TAU(NROWT,NCOLT),OVRLP(1),Z(1),IOVOFF(NIRREP)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
C
C LOOP OVER IRREPS OF A AND J
C
       INDAJ=0
       INDOV=1
       IOFTL0=1
       IOFTR0=0
       DO 200 IRREPAJ=1,NIRREP
        IRREPBI=DIRPRD(IRREPAJ,IRREPDO)
        INDOV=IOVOFF(IRREPBI)
        VRTB=VRT(IRREPBI,2)
        POPI=POP(IRREPBI,1)
        VRTA=VRT(IRREPAJ,1)
        POPJ=POP(IRREPAJ,2)
        IBI=1
        DO 210 J=1,POPJ
         IOFTRX=IOFTR0+(J-1)*POPI
         DO 220 A=1,VRTA
          INDAJ=INDAJ+1
          IOFTL=IOFTL0+(A-1)*VRTB
          DO 230 I=1,POPI
           IOFTR=IOFTRX+I
           Z(INDAJ)=Z(INDAJ)+SDOT(VRTB,TAU(IOFTL,IOFTR),1,
     &              OVRLP(INDOV+I),POPI)
230       CONTINUE
220      CONTINUE
210     CONTINUE
        IOFTR0=IOFTR0+POPI*POPJ
        IOFTL0=IOFTL0+VRTA*VRTB
200    CONTINUE
       RETURN
       END
