      SUBROUTINE UPJSD(JSD,JSD2,JSD3,SCR1,SCR2,NCOORD,NIRREP,UPDATE)
C
CEND
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DOUBLE PRECISION JSD,JSD2,JSD3
      LOGICAL UPDATE 
C
      DIMENSION JSD(NCOORD,NCOORD),JSD2(NCOORD/2,NCOORD/2),
     &          JSD3(NCOORD/2,NCOORD/2),SCR1(1),SCR2(1)
C
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALOBE,IBITWD
C
      DATA IONE/1/
      DATA ONE,TWO,FOUR,EIGHT,NINE/1.D0,2.D0,4.D0,8.D0,9.D0/
C
C C: VELOCITY OF LINGHT IN A.U.
C
      DATA C /137.035987D0/
C
C MPROTON: MASS OF PROTON IN A.U.
C
      DATA MPROTON /1836.152736D0/
C
C CONVERT: CONVERSION FROM A.U. TO SEC  (FOR TIME UNITS)
C
      DATA  CONVERT /2.4188843D-17/
C
      DATA PI /3.141592654D0/
C
C CONVERSION OF CALCULATED COUPLING TENSOR TO THE USUAL UNITS (HZ)
C
      FACT=ONE/(TWO*EIGHT*(MPROTON**2)*(C**4)*CONVERT*TWO*NINE*PI)
C
      CALL SSCAL(NCOORD*NCOORD,FACT,JSD,1)
C
      IF(NIRREP.NE.1) THEN
C 
       CALL ZERO(JSD2,NCOORD*NCOORD)
       CALL TRAHES(JSD,JSD2,SCR1,SCR2,NCOORD)
c YAU : old
c      CALL ICOPY(NCOORD*NCOORD*IINTFP,JSD2,1,JSD,1)
c YAU : new
       CALL DCOPY(NCOORD*NCOORD,JSD2,1,JSD,1)
c YAU : end
C
      ENDIF
C
      CALL REDJSD(JSD,JSD2,NCOORD)
C
      CALL GETREC(20,'JOBARC','NINDATOM',IONE,NUCIND)
      CALL GETREC(20,'JOBARC','MULTATOM',NUCIND,SCR1)
      CALL GETREC(20,'JOBARC','NAMCOORD',IINTFP*3*NUCIND,
     &            SCR1(1+NUCIND))
C
      CALL JPRI(JSD2,NCOORD/2,NUCIND,SCR1,SCR1(1+NUCIND),SCR2,.TRUE.)
C
      IF(UPDATE) THEN
 
       OPEN(UNIT=81,FILE='JSD',STATUS='OLD',FORM='FORMATTED')
       DO 2000 ICOORD=1,NCOORD/2
        READ(81,3001) (JSD3(ICOORD,J),J=1,NCOORD/2)
2000   CONTINUE
3000   FORMAT(2I5)
3001   FORMAT(3F20.10)
       CALL SAXPY(NCOORD*NCOORD/4,ONE,JSD3,1,JSD2,1)
      ELSE
       OPEN(UNIT=81,FILE='JSD',STATUS='UNKNOWN',FORM='FORMATTED')
      ENDIF
C
      REWIND(81)
      DO 2100 ICOORD=1,NCOORD/2
       WRITE(81,3001) (JSD2(ICOORD,J),J=1,NCOORD/2)
2100  CONTINUE
      CLOSE(UNIT=81,STATUS='KEEP')
C
      RETURN
      END
