      SUBROUTINE DRMOVE(ICORE,MAXCOR,IUHF,NLIST,SING1)
C
C DRIVER FOR CALLS WHICH MOVE THE T AMPLITUDE INCREMENT LISTS (LIST 61 - 63
C AND 90-91) INTO THE REFERENCE T AMPLITUDE LIST AREA (LIST 44+NLIST - 46+
C NLIST AND 90+NLIST 91+NLIST)
C
C NLIST = 0   USUAL REFERENCE LIST    NLIST=100   LAMBDA REFERENCE LIST
C
C SING1 = TRUE, SINGLES SHOULD BE MOVED AS WELL
C SING1 = FALSE, NO SINGLES 
C
CEND
      IMPLICIT INTEGER (A-Z)
      LOGICAL SING1
      DIMENSION ICORE(MAXCOR)
      COMMON /INFO/ NOCCO(2),NVRTO(2)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ ISTART,NIRREP,IRREPA(255),IRREPB(255),
     &                DIRPRD(8,8)
      COMMON /SYM/ POP1(8),POP2(8),VRT1(8),VRT2(8),NTAA,NTBB,
     &             NF1AA,NF1BB,NF2AA,NF2BB
      COMMON /FLAGS/ IFLAGS(100)
C
C DO AA SPIN CASE.
C
      DO 10 ISPIN=1,IUHF+1
       CALL MVSYM(ICORE,MAXCOR,IUHF,1,60+ISPIN,43+ISPIN+NLIST)
10    CONTINUE
C
C DO AB SPIN CASE
C
      CALL MVSYM(ICORE,MAXCOR,IUHF,1,63,46+NLIST)
C
C     SINGLES IN CCSD AND QCISD
C
      IF(.NOT.SING1) RETURN
C
      CALL MVLIST(ICORE,NTAA,1,90,90+NLIST,3,1,1,1)
      IF(IUHF.EQ.1) CALL MVLIST(ICORE,NTBB,1,90,90+NLIST,4,2,1,1)
      RETURN
      END
