
      SUBROUTINE NEWTYP(LIST,SYTYPL,SYTYPR,CHANGE)
      IMPLICIT NONE
      INTEGER LIST,SYTYPL,SYTYPR
      LOGICAL CHANGE
      CALL ACES_FAMILY_REDIST(1,LIST,SYTYPL,SYTYPR,CHANGE)
      RETURN
      END

