
C ROUTINE PRINTS FIRST LENGTH ELEMENTS OF INTEGER VECTOR IVEC,
C ALONG WITH THE CORRESPONDING INDICES IN I5,I6 FORMAT.

      SUBROUTINE PRVECI(IVEC,LENGTH)
      IMPLICIT INTEGER (A-Z)
      DIMENSION IVEC(LENGTH)
      if (length.lt.1) return
      WRITE(*,100) (I,IVEC(I),I=1,LENGTH)
100   FORMAT(5(1X,:'[',I5,']',I6))
      RETURN
      END
