      SUBROUTINE RLELST(ICORE,MAXCOR,IUHF,SINGLE,RLETYP)
C
C THIS ROUTINE CREATES THE T AMPLITUDE LISTS USED BY THE 
C  RLE PROGRAM.
C
CEND
      IMPLICIT INTEGER (A-Z)
      LOGICAL SINGLE
      DIMENSION ICORE(MAXCOR)
      COMMON /FLAGS/ IFLAGS(100)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYM/ POP(8,2),VRT(8,2),NTAA,NTBB,NF1AA,NF1BB,
     &             NF2AA,NF2BB
      NRLE=IFLAGS(12)+1
      DO 110 ISPIN=3,1,IUHF-2
       SIZE=ISYMSZ(ISYTYP(1,60+ISPIN),ISYTYP(2,60+ISPIN))
       IF(SINGLE)THEN
        IF(ISPIN.EQ.1)SIZE=SIZE+NTAA
        IF(ISPIN.EQ.2)SIZE=SIZE+NTBB   
       ENDIF
       CALL UPDMOI(NRLE,SIZE,ISPIN,70,0,0)
       IF(RLETYP.EQ.2.OR.RLETYP.EQ.3)THEN
       CALL UPDMOI(NRLE,SIZE,ISPIN+3,70,0,0)
       ENDIF
110   CONTINUE
      DO 120 ISPIN=3,1,IUHF-2
       SIZE=ISYMSZ(ISYTYP(1,60+ISPIN),ISYTYP(2,60+ISPIN))
       IF(SINGLE)THEN
        IF(ISPIN.EQ.1)SIZE=SIZE+NTAA
        IF(ISPIN.EQ.2)SIZE=SIZE+NTBB   
       ENDIF
       CALL UPDMOI(1,SIZE,ISPIN,89,0,0)
120   CONTINUE
      RETURN
      END
