
C THIS ROUTINE SYMMETRIZES A GIVEN MATRIX A
C
C   A(PQ) = 1/2 ( A(PQ)+A(QP))
C
C WHERE A IS A SYMMETRY PACKED MATRIX AND
C NUM THE CORRESPONDING POPULATION VECTOR
C
C THE SYMMETRIZATION IS HERE COMPLETELY DONE IN PLACE
C
C CODED AUGUST/90 JG

      SUBROUTINE SYMMET2(A,NUM)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DIMENSION A(NUM,NUM)

      if (num.lt.2) return

C SYMMETRIZE FIRST HALF OF A
      DO I = 2, NUM
         DO J = 1, I-1
            A(I,J) = 0.5d0*(A(I,J)+A(J,I))
         END DO
      END DO

C FILL SECOND HALF OF A
      DO I = 2, NUM
         DO J = 1, I-1
            A(J,I) = A(I,J)
         END DO
      END DO

      RETURN
      END
