      SUBROUTINE TRADIP(SDIPDR,CDIPDR,TRSTOC,NCOOR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION SDIPDR(3,1),CDIPDR(3,1),TRSTOC(1)
      PARAMETER (AZERO=0.0D0)
      PARAMETER (ONE  =1.0D0)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/PERT/NTPERT,NPERT(8),IPERT(8),IXYZ(3)       
      CALL GETREC(20,'JOBARC','SYMCOORD',IINTFP*NCOOR*NCOOR,TRSTOC)
      CALL XGEMM('N','T',3,NCOOR,NCOOR,
     &           ONE,  SDIPDR,3,
     &                 TRSTOC,NCOOR,
     &           AZERO,CDIPDR,3)
      RETURN
      END
