      SUBROUTINE TRAHES(SHESS,CHESS,MATRIX,TRSTOC,NCOOR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION SHESS(1), CHESS(1),
     &          MATRIX(1),TRSTOC(1)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      PARAMETER (AZERO=0.D0)
      PARAMETER (ONE=1.D0)

C READ IN THE TRANSFORMATION MATRIX
      CALL GETREC(20,'JOBARC','SYMCOORD',IINTFP*NCOOR*NCOOR,TRSTOC)

C TRANSFORM RIGHT AND LEFT HAND SIDE COORDINATES
      CALL XGEMM('N','N',NCOOR,NCOOR,NCOOR,
     &           ONE,  TRSTOC,NCOOR,
     &                 SHESS, NCOOR,
     &           AZERO,MATRIX,NCOOR)
      CALL XGEMM('N','T',NCOOR,NCOOR,NCOOR,
     &           ONE,  MATRIX,NCOOR,
     &                 TRSTOC,NCOOR,
     &           AZERO,CHESS, NCOOR)

      RETURN
      END
