      SUBROUTINE GETDPT
C
C FORMS THE VMOL DIRECT PRODUCT TABLE.  CODE IS STRAIGHT OUT
C  OF VMOL, EXCEPT THAT THE IDIOTIC VARIABLE NAMES (AND, OR AND
C  EOR) HAVE BEEN CHANGED TO SOMETHING LESS DANGEROUS.
C
CEND
      IMPLICIT INTEGER (A-Z)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &DIRPRD(8,8)
      COMMON /CONTROL/ IPRNT,IXXX,IXXX2
      COMMON /FILES/ LUOUT,MOINTS
      KA(I,K)=(I-1)/(2**(K-1))-2*((I-1)/(2**K))
      DO 108 I=1,8
      DO 108 J=1,8
      IAN=1
      IOR=1
      DO 102 K=1,3
      IAN=IAN+MIN(KA(I,K),KA(J,K))*2**(K-1)
  102 IOR=IOR+MAX(KA(I,K),KA(J,K))*2**(K-1)
      DIRPRD(I,J)=IOR-IAN+1
  108 CONTINUE
      IF(IPRNT.GT.10)THEN
       WRITE(LUOUT,400)
400    FORMAT(T3,'@GETDPT-I, Direct product table:')
       DO 33 I=1,NIRREP
        WRITE(LUOUT,500)(DIRPRD(I,J),J=1,NIRREP)
33     CONTINUE
500    FORMAT(T20,8I3)
      ENDIF
      RETURN
      END
