
C THIS ROUTINE PRINTS OUT A SUMMARY OF ALL RECORDS IN THE JOBARC FILE,
C THEIR LOCATION (WORD ADDRESS) AND THE NUMBER OF INTEGER WORDS THAT
C THE LOGICAL RECORD TAKES UP.

      SUBROUTINE JASMRY
      IMPLICIT INTEGER (A-Z)
      CHARACTER*8 MARKER
      PARAMETER (LENGTH = 1000)
      COMMON /JOBARC/ MARKER(LENGTH),LOC(LENGTH),SIZE(LENGTH),NRECS,
     &                IRECWD,IRECLN
      WRITE(*,30)
30    FORMAT(T14,'Summary of JOBARC file contents',/,
     &       T5,'LABEL',T25,'FILE LOCATION',T54,'LENGTH',/,
     &       T22,'(absolute word offset)',T50,'(integer words)')
      DO I = 1, 1000
         IF (MARKER(I).EQ.'OPENSLOT') GOTO 20
         WRITE(*,'(T3,A8,T26,I9,T51,I9)') MARKER(I),LOC(I),SIZE(I)
      END DO
20    CONTINUE
      RETURN
      END
