      SUBROUTINE KILLDER
C
C THIS ROUTINE DISPENSES WITH THE DERGAM FILE AND ZEROS OUT ALL OF
C  THE ASSOCIATED LIST POINTERS
C
CEND
      IMPLICIT INTEGER(A-Z)
      LOGICAL YESNO,ISOPEN
      COMMON /LISTS/ MOIO(10,500),MOIOWD(10,500),MOIOSZ(10,500),
     &              MOIODS(10,500),MOIOFL(10,500)
      COMMON /CACHEINF/ CACHNUM,CACHNMP1,CACHDIR(100),CACHPOS(100),
     &                  CACHFILE(100),CACHMOD(100),OLDEST
      INQUIRE(FILE='DERGAM',EXIST=YESNO,OPENED=ISOPEN)
      IF(YESNO) THEN
      IF(.NOT.ISOPEN)OPEN(UNIT=54,FILE='DERGAM',STATUS='OLD')
      CLOSE(UNIT=54,STATUS='DELETE')
      CALL IZERO(MOIO(1,401),1000)
      CALL IZERO(MOIOWD(1,401),1000)
      CALL IZERO(MOIODS(1,401),1000)
      CALL IZERO(MOIOSZ(1,401),1000)
      CALL IZERO(MOIOFL(1,401),1000)
C
      DO 10 I=1,100
C
       IF(CACHFILE(I).EQ.54)THEN
        CACHFILE(I)=0
        CACHDIR (I)=0
       ENDIF
10    CONTINUE   
      ENDIF
      RETURN
      END
