      SUBROUTINE TRNCHR(LIST1,LIST2)
C
C THIS ROUTINE CHANGES THE CHARACTERISTICS OF A LIST, ALLOWING
C  ITS TRANSPOSE TO BE WRITTEN IN THE SAME AREA.  USED IN THE
C  FULL GAMMA BACK-TRANSFORMATION.
C  
C INPUT: LIST1  - THE SECONDARY LIST NUMBER.
C        LIST2  - THE PRIMARY LIST NUMBER.
C
CEND
      IMPLICIT INTEGER (A-Z)
      LOGICAL CHANGE
      COMMON /IOPOS/ ICRSIZ,ICHCSZ,IOFF(2),LENREC
      COMMON /LISTS/ MOIO(10,500),MOIOWD(10,500),MOIOSZ(10,500),
     &              MOIODS(10,500),MOIOFL(10,500)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &                DIRPRD(8,8)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      ITMP=MOIODS(LIST1,LIST2)
      MOIODS(LIST1,LIST2)=MOIOSZ(LIST1,LIST2)
      MOIOSZ(LIST1,LIST2)=ITMP
      RETURN
      END
