      SUBROUTINE WRDIR(IUNIT,IREC,IVEC,LENGTH,IMOD)
C
C WRITES A RECORD TO DIRECT ACCESS UNIT IUNIT.
C
C  INPUT:
C        IUNIT - UNIT NUMBER FOR DIRECT ACCESS FILE.
C        IREC  - NUMBER OF RECORD TO BE WRITTEN.
C        IVEC  - VECTOR TO BE WRITTEN.
C        LENGTH- LENGTH OF VECTOR IN *INTEGER* WORDS.
C        IMOD  - RETURNED AS ZERO.
C
C NOTE: THIS ROUTINE IS A DEPENDENT OF GETLST AND PUTLST.  IF THE
C        SPECIFIED RECORD NUMBER IS <0, IT WILL SIMPLY RETURN RATHER
C        THAN CAUSING AN ERROR EXIT.  ALL PEOPLE WHO USE THIS ROUTINE
C        SHOULD BE AWARE OF THIS.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DIMENSION IVEC(LENGTH)
      IMOD=0
      IF(IREC.LE.0)RETURN
      WRITE(IUNIT,REC=IREC,ERR=555,IOSTAT=IER)IVEC
      RETURN
555   CALL IOERR('WRDIR',IUNIT,IER)
      END
