
C THIS ROUTINE INITIALIZES ALL RECORDS IN THE JOBARC FILE, STARTING
C AFTER THE EXISTING RECORD SPECIFIED BY THE LABEL WHICH IS PASSED IN

      SUBROUTINE ZEROJA(LABEL)
      IMPLICIT INTEGER (A-Z)
      CHARACTER*8 LABEL
      CHARACTER*8 MARKER
      PARAMETER (LENGTH = 1000)
      COMMON /JOBARC/ MARKER(LENGTH),LOC(LENGTH),SIZE(LENGTH),NRECS,
     &                IRECWD,IRECLN

      IPOS = LOCCHR(LENGTH,MARKER,1,LABEL) + 1
      IF (IPOS.EQ.LENGTH+1) RETURN

      CALL IZERO(LOC(IPOS),LENGTH-IPOS+1) 
      CALL IZERO(SIZE(IPOS),LENGTH-IPOS+1) 
      DO I = IPOS, LENGTH
         MARKER(I) = 'OPENSLOT'
      END DO

      RETURN
      END
