      DOUBLE PRECISION FUNCTION ANGLE(A,B,N)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(N),B(N)
      DTOR=DACOS(-1.D0)/180.D0
      Z = xdot(N,A,1,B,1)
C
C MAKE SURE A VALUE OF SLIGHTLY MORE THAN ONE DOES NOT GET PASSED
C  TO DACOS
C
      ANGLE=DACOSX(Z,1.D-10)/DTOR
      RETURN
      END
