      SUBROUTINE COMPARE(Q1,Q2,ATMASS,IMAP,NATOM,IERR,TOL)
C
C THIS ROUTINE CHECKS WHETHER COORDINATE VECTORS Q1 AND
C Q2 ARE RELATED BY A SIMPLE PERMUTATION.  IF THEY ARE,
C IERR IS RETURNED AS "0", AND IMAP CONTAINS THE PERMUTATION
C VECTOR
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL IMATCH
      DIMENSION Q1(3*NATOM),Q2(3*NATOM),ATMASS(NATOM),IMAP(NATOM)
      DIMENSION TMP(3)
C
      DATA ZILCH / 0.0/
      DATA ONEM  /-1.0/ 
C
      IERR=0
      IOFF1=1
      CALL IZERO(IMAP,NATOM)
      DO 10 IATOM1=1,NATOM
       IF(ATMASS(IATOM1).NE.ZILCH)THEN
        IOFF2=1
        IMATCH=.FALSE.
        DO 20 IATOM2=1,NATOM
         IF(ATMASS(IATOM2).EQ.ATMASS(IATOM1))THEN
          CALL VADD(TMP,Q1(IOFF1),Q2(IOFF2),3,ONEM)
          I=ISAMAX(3,TMP,1)
          IF(ABS(TMP(I)).LT.TOL)THEN
           IMAP(IATOM1)=IATOM2
           IMATCH=.TRUE.
          ENDIF
         ENDIF
         IOFF2=IOFF2+3
20      CONTINUE
        IF(.NOT.IMATCH)IERR=IERR+1
       ENDIF
       IOFF1=IOFF1+3
10    CONTINUE
C
      RETURN
      END
