        SUBROUTINE PIKSR3(N,ARR,NLIST)
C
C SIMPLE SORTER FROM NUMERICAL RECIPES.
C
CEND
        IMPLICIT DOUBLE PRECISION (A-H,O-Z)
        DIMENSION ARR(N),NLIST(N)
        DO 12 J=2,N
        A=ARR(J)
        NLST=NLIST(J)
        DO 11 I=J-1,1,-1
         IF(ARR(I).GE.A)GOTO 10
         ARR(I+1)=ARR(I)
         NLIST(I+1)=NLIST(I)
   11   CONTINUE
        I=0
   10   ARR(I+1)=A
        NLIST(I+1)=NLST
   12   CONTINUE
        RETURN
        END
