      SUBROUTINE REFLECT(A,SCRATCH,NATOM,IPLANE)
C
C REFLECTS POINTS IN PLANE
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(3,NATOM),SCRATCH(3,NATOM)
C
      IX(I,J)=MIN(I,J)/MAX(I,J)
C
      DO 10 I=1,NATOM
         DO 10 J=1,3
 10         SCRATCH(J,I)=A(J,I)*(1.D0-2.D0*IX(IPLANE,J))
C
      RETURN
      END
