      SUBROUTINE SQUSH(VEC,LEN)
C
C SUBROUTINE USED TO "SQUASH" R VECTOR.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION VEC(LEN)
      VEC(1)=VEC(4)
      VEC(2)=VEC(7)
      VEC(3)=VEC(8)
      DO 10 I=4,LEN-6
      VEC(I)=VEC(I+6)
 10   CONTINUE
      CALL ZERO(VEC(MAX(LEN-5,2)),6)
      RETURN
      END
