
      SUBROUTINE STRIPDUM(IPTR,ATMASS,NATOM,NTOTAL,NSYOP,IHOLD)
C
C STRIP DUMMY ATOMS OUT OF PERMUTATION ARRAY
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION IPTR(NTOTAL,NSYOP),ATMASS(*),IMAPZ2R(150)
      DIMENSION IMAPR2Z(150),IHOLD(NTOTAL,NSYOP)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      CALL GETREC(20,'JOBARC','ATOMMASS',IINTFP*NTOTAL,ATMASS)
      CALL IZERO(IMAPZ2R,NTOTAL*NSYOP)
      CALL IZERO(IMAPR2Z,NTOTAL*NSYOP)
      CALL ICOPY (NTOTAL*NSYOP, IPTR, 1, IHOLD, 1)

      IREAL=0
      DO 10 IATOM=1,NTOTAL
       IF(ATMASS(IATOM).NE.0.0D0)THEN
        IREAL=IREAL+1
        IMAPR2Z(IREAL)=IATOM
        IMAPZ2R(IATOM)=IREAL
       ENDIF
10    CONTINUE
C
      DO 20 IOP=1,NSYOP
       DO 30 IATOM=1,NATOM
        JATOM=IMAPR2Z(IATOM)
        KATOM=IHOLD(JATOM,IOP)
        IPTR(IATOM,IOP)=IMAPZ2R(KATOM)
30     CONTINUE
20    CONTINUE
C
      RETURN
      END        
