      SUBROUTINE UNITRY(A,B,C,N)
C
C PERFORMS UNITARY TRANSFORMATION C = A(t) B A
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(N,N),B(N,N),C(N,N)
      CALL MODMATMUL(C,B,A,N,N,N,N,N,N)
      CALL MTRAN2(A,N)
      CALL MODMATMUL(C,A,C,N,N,N,N,N,N)
      CALL MTRAN2(A,N)
      RETURN
      END
