      SUBROUTINE WRITE_WARN_LOG(WARN_STRING)
 
      IMPLICIT NONE
      CHARACTER*80 WARN_STRING
      INTEGER IUNIT

      PARAMETER(IUNIT=10)

      OPEN(UNIT=IUNIT, FILE='WARN.LOG', FORM='FORMATTED')
     
      IF (WARN_STRING .EQ. 'INVALID SUBGROUP') THEN
          WRITE(IUNIT) 'Warning:'
      ENDIF
   
      CLOSE (IUNIT) 
      RETURN
      END 
