      SUBROUTINE COPY(SOURCE,TARGET,LENGTH)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION SOURCE(LENGTH),TARGET(LENGTH)
      DO 10 I=1,LENGTH
       TARGET(I)=SOURCE(I)
10    CONTINUE
      RETURN
      END
