      SUBROUTINE FILPOP
C
C FILLS THE SYMMETRY POPULATION VECTOR COMMON BLOCK.
C
CEND
      IMPLICIT INTEGER (A-Z)
      CHARACTER*6 SYMLST(22)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),NTOT(18)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &                DIRPRD(8,8)
      DATA SYMLST /'SVAVA0','SVBVB0','SOAOA0','SOBOB0',
     &             'SVAVA1','SVBVB1','SOAOA1','SOBOB1',
     &             'SVAOA2','SVBOB2','SOBVA2','SVBOA2',
     &             'SVAVB2','SOAOB2','SVAVB2','SOAVA2',
     &             'SOBVB2','SOAVB2','SVAVA2','SVBVB2',
     &             'SOAOA2','SOBOB2'/
      CALL IZERO(IRPDPD,144)
      DO 10 ITYPE=1,22
       CALL GETREC(-1,'JOBARC',SYMLST(ITYPE)//'X ',NIRREP,
     &             IRPDPD(1,ITYPE))
10    CONTINUE
      RETURN
      END
