      SUBROUTINE GETSTF(EVAL,IUHF,IENTRY)
C
C THIS ROUTINE IS A DEPENDENT OF CRAPSI AND INITIALIZES MANY
C  OF THE COMMON BLOCKS USED BY THE PROGRAM SYSTEM.  CALLING
C  THIS ROUTINE EXPLICITLY IS NOT A WISE THING TO DO.
C
CEND
C
CJDW 3/21/94
C Addition of IFLAGS2.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL YESNO,LINCC,CICALC
      CHARACTER*3 CALTYP
      CHARACTER*8 TYPEO
      CHARACTER*6 FILE1
      CHARACTER*80 FNAME
      INTEGER DIRPRD,QUIKGET
      DIMENSION EVAL(1)
      COMMON /LISTS/ MOIO(10,500),MOIOWD(10,500),MOIOSZ(10,500),
     &               MOIODS(10,500),MOIOFL(10,500)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /FILES/ LUOUT,MOINTS
      COMMON /FILSPC/ ILNBUF,IPRCLN,IPRCWD
      COMMON /INFO/ NOCCO(2),NVRTO(2)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &DIRPRD(8,8)
      COMMON /SYMLOC/ ISYMOFF(8,8,25)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),NTOT(18)
      COMMON /CONTROL/ IPRNT,IXXX,IXXX2
      COMMON /FLAGS/ IFLAGS(100)
      COMMON /FLAGS2/ IFLAGS2(500)
      COMMON /LINEAR/ LINCC,CICALC
      COMMON /AUXCACHE/ QUIKGET(10,500)
      MOIOSIZ=5000
      IONE=1
      ITWO=2
      ISIXTN=16
      ISIXFR=64
      NPARAM=100
      NPARAM2=500
      IUHF=0
      LINCC=.FALSE.
      CICALC=.FALSE.
      CALL IZERO(QUIKGET,5000)
      CALL GETREC(-1,'JOBARC','IFLAGS  ',NPARAM,IFLAGS)
      CALL GETREC(-1,'JOBARC','IFLAGS2 ',NPARAM2,IFLAGS2)
      CALL GETREC(-1,'JOBARC','NOCCORB ',ITWO,NOCCO)
      CALL GETREC(-1,'JOBARC','NVRTORB ',ITWO,NVRTO)
      CALL GETREC(-1,'JOBARC','COMPNIRR',IONE,NIRREP)
      CALL GETDPT
      IF(IFLAGS(11).GE.1)IUHF=1
      NORBS=NOCCO(1)+NVRTO(1)
      CALTYP='RHF'
      IF(IUHF.EQ.1)CALTYP='UHF'
      CALL FILPOP
      CALL INITPOP
c      CALL GETREC(-1,'JOBARC','IRREPALP',NORBS,IRREPA)
c      CALL GETREC(-1,'JOBARC','IRREPBET',NORBS,IRREPB)
      CALL GETREC(-1,'JOBARC','MOIOVEC ',MOIOSIZ,MOIO)
      CALL GETREC(-1,'JOBARC','MOIOWRD ',MOIOSIZ,MOIOWD)
      CALL GETREC(-1,'JOBARC','MOIOSIZ ',MOIOSIZ,MOIOSZ)
      CALL GETREC(-1,'JOBARC','MOIODIS ',MOIOSIZ,MOIODS)
      CALL GETREC(-1,'JOBARC','MOIOFIL ',MOIOSIZ,MOIOFL)
      CALL GETREC(-1,'JOBARC','ISYMTYP ',1000,ISYTYP)
      CALL GFNAME('MOINTS  ',FNAME,ILENGTH)
      INQUIRE(FILE=FNAME(1:ILENGTH),EXIST=YESNO)
      IF(YESNO.AND.IENTRY.NE.-1)THEN
       CALL UPDMOI(0,0,0,0,3,0)
       IJUNK = 0
       CALL INITIO(IJUNK,I0) 
      ENDIF
      CALL GNSYOF
      RETURN
      END
